[package]
name = "cowlang"
version = "0.1.0"
authors = ["Kai Mast <kaimast@cs.cornell.edu>"]
edition = "2018"

[dependencies]
pyo3 = { version="0.9", optional=true }
bincode = { version="1.2" }
serde = { version="1.0", features=["derive"] }
#plex = { version="0.2" }
plex = { git="https://github.com/kaimast/plex.git" }

[features]
default = []
verbose = []
python-bindings = ["pyo3"]
