[package]
name = "cowlang"
version = "0.1.0"
authors = ["Kai Mast <kaimast@cs.cornell.edu>"]
edition = "2018"

[dependencies]
pyo3 = { version="0.11", optional=true }
bincode = { version="1.2" }
serde = { version="1.0", features=["derive"] }
bytes = { version="0.5", features=["serde"] }
plex = { git="https://github.com/kaimast/plex.git", optional=true }

[features]
default = ["compiler", "interpreter"]
verbose = []
python-bindings = ["pyo3"]
compiler = ["plex"]
interpreter = []
