// Hide warnings generated by Plex
#![ allow(clippy::redundant_closure_call, clippy::unused_unit, clippy::match_single_binding, clippy::let_unit_value, clippy::unit_arg, clippy::comparison_chain, clippy::unnested_or_patterns, unused_braces) ]

#![feature(map_first_last)]

pub mod ast;

mod values;
pub use values::*;

#[ cfg(feature="compiler") ]
mod compiler;
#[ cfg(feature="compiler") ]
pub use compiler::*;

#[ cfg(feature="interpreter") ]
pub mod interpreter;
#[ cfg(feature="interpreter") ]
pub use interpreter::{Interpreter, Module};
