name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
 
    steps:
    - uses: actions/checkout@v4
    - name: Install rustc and clippy
      uses: dtolnay/rust-toolchain@stable
      with:
         toolchain: stable 
         components: cargo, rustc, clippy, rustfmt
    - name: Build
      run: |
        cargo build --verbose
        cargo build --package=cowlang-derive --verbose
    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --package=cowlang-derive --verbose
    - name: Check formatting
      run: |
        cargo fmt --check
        cargo fmt --package=cowlang-derive --check
 
